### ISSUE TITLE
[functionality] Parent-handling of TST entries

### ISSUE THREAD

**Issue by matthiasbeyer** [vitiral/artifact#214] opened 2018-01-06 15:30 UTC
I have the following setup:

* `REQ-bin`
* `SPC-bin`
* `SPC-bin-stdcli`
* `TST-bin-stdcli`

But that fails as `TST-bin` is expected. But there is - at least in my case - no way of defining `TST-bin` (it is semantically not valid to actually do this) - and there is a valid parent entry (`SPC-bin-stdcli`) ... so it would be nice if that would be supported.

**Comment by vitiral** [comment] 2018-01-06 16:17
A bit of history: we used to auto-create parents if they didn't exist. That behavior created a lot of spam and was reverted before the 1.0 release -- but we still required that the parent exists.

I think it would be a good idea to remove that requirement as well (I was being conservative before). Note that this does not break backwards compatibility.

**Comment by vitiral** [comment] 2018-01-06 16:18
labeling as an enhancement since it is curently "working as intended".

This will be fixed as partof the rewrite of core. I was actually *just going to implement a lint* for this -- now I have less work to do! Yay for features *reducing* your work :smile:

**Comment by vitiral** [comment] 2018-11-06 15:48
this was fixed in 2.0!

**Closed by vitiral** 2018-11-06 15:48 UTC
Labels: enhancement
