### ISSUE TITLE
art init -t flag error

### ISSUE THREAD

**Issue by evelynmitchell** [vitiral/artifact#106] opened 2017-03-13 17:34 UTC
In a new directory:
art ls
Encountered Error:

Could not find .art folder. Try running `art init -t`

And then,
art init -t

gives an error, because -t is not a valid flag.

**Comment by vitiral** [comment] 2017-03-13 17:43
Duplicate of #99 will be fixed in next release

**Closed by vitiral** 2017-03-13 17:43 UTC
Labels: duplicate
